clc;
clear all;
close all;
fp=input('Enter the pass band edge frequency: ');
fs=input('Enter the stop band edge frequency: ');
rp=input('Enter the ripple in pass band: ');
rs=input('Enter the ripple in stop band: ');
Fs=20*max(fs,fp);
wp=2*(fp/Fs);
ws=2*(fs/Fs);
[N1,wc1]=cheb1ord(wp,ws,rp,rs);
[a1,b1]=cheby1(N1,rp,wc1,'high');
[N2,wc2]=cheb2ord(wp,ws,rp,rs);
[a2,b2]=cheby2(N2,rs,wc2,'high');
[H1,w]=freqz(a1,b1);
[H2,w]=freqz(a2,b2);
Hmag1=abs(H1);
Hmag2=abs(H2);
h1=Hmag1/max(Hmag1);
h2=Hmag2/max(Hmag2);
x=(w*Fs)/(2*pi);
plot(x,20*log10(h1),'r',x,20*log10(h2),'b');
title('Chebyshev1,chebyshev2 Highpass filter');
xlabel('Frequency(Hz)');
ylabel('Magnitude(dB)');
legend('Chebyshev 1','Chebyshev 2');
